# Generated by Django 5.0.4 on 2024-05-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_converter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
