# Generated by Django 5.0.3 on 2024-03-18 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_movie_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(choices=[(5, 'NC-17'), (1, 'G'), (2, 'PG'), (3, 'PG-13'), (4, 'R')]),
        ),
    ]
