# Generated by Django 5.0.3 on 2024-03-18 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_movie_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(choices=[(2, 'PG'), (3, 'PG-13'), (4, 'R'), (1, 'G'), (5, 'NC-17')]),
        ),
    ]
