# Generated by Django 5.0.3 on 2024-04-24 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_alter_movie_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(choices=[(1, 'G'), (5, 'NC-17'), (2, 'PG'), (3, 'PG-13'), (4, 'R')]),
        ),
    ]
